import { jsPDF } from "jspdf";

type TaxType =
  | "VAT"
  | "WHT"
  | "CIT"
  | "PIT"
  | "CGT"
  | "STAMP_DUTY"
  | "TET"
  | "POLICE_LEVY"
  | "NASENI"
  | "OTHER";

export interface TaxRemittancePdfPayload {
  taxpayerName: string;
  businessName?: string;
  taxType: TaxType;
  period: string;
  dueDate: string;
  taxAmount: number;
  scheduleId: string;
  generatedAt?: string;
  paymentReference?: string;
}

const formatCurrency = (amount: number): string =>
  `NGN ${Math.max(0, amount).toLocaleString("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const formatDate = (value: string): string =>
  new Date(value).toLocaleDateString("en-NG", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

const makeFirsPaymentReference = (
  taxType: string,
  period: string,
  generatedAtIso: string,
  amount: number
): string => {
  const dateCode = generatedAtIso.slice(0, 10).replace(/-/g, "");
  const amountCode = Math.round(Math.abs(amount)).toString().slice(-4).padStart(4, "0");
  const periodCode = period.replace(/[^a-zA-Z0-9]/g, "").toUpperCase();
  return `FIRS-${taxType}-${periodCode}-${dateCode}-${amountCode}`;
};

const cleanFileName = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

export function generateTaxRemittancePdf(payload: TaxRemittancePdfPayload): string {
  const generatedAtIso = payload.generatedAt || new Date().toISOString();
  const paymentReference =
    payload.paymentReference ||
    makeFirsPaymentReference(payload.taxType, payload.period, generatedAtIso, payload.taxAmount);

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = 18;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Tax Remittance Record", margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Official payment record for tax remittance processing", margin, y);
  y += 10;

  doc.setDrawColor(225, 225, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("FIRS Payment Reference", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(paymentReference, margin, y);
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Remittance Slip", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const slipRows: Array<[string, string]> = [
    ["Taxpayer", payload.taxpayerName || "Not provided"],
    ["Business", payload.businessName || "Not provided"],
    ["Tax Type", payload.taxType],
    ["Tax Period", payload.period],
    ["Amount Payable", formatCurrency(payload.taxAmount)],
    ["Due Date", formatDate(payload.dueDate)],
    ["Generated On", formatDate(generatedAtIso)],
    ["Schedule ID", payload.scheduleId],
    ["Payment Authority", "Federal Inland Revenue Service (FIRS)"],
  ];

  for (const [label, value] of slipRows) {
    doc.setFont("helvetica", "bold");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 38, y);
    y += 6;
  }

  y += 3;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Payment Instructions", margin, y);
  y += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const instructions = [
    "1. Use the FIRS payment reference above when initiating payment.",
    "2. Submit payment through approved bank channels or FIRS digital rails.",
    "3. Keep bank confirmation and remittance evidence for compliance records.",
    "4. File and reconcile this remittance against the related tax schedule.",
  ];

  instructions.forEach((line) => {
    const wrapped = doc.splitTextToSize(line, pageWidth - margin * 2);
    doc.text(wrapped, margin, y);
    y += wrapped.length * 5 + 1;
  });

  y += 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Integration Note", margin, y);
  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  const integrationText =
    "Possible integration point: FIRS ATRS / TaxPro Max payment flow or designated bank payment gateway.";
  const wrappedIntegration = doc.splitTextToSize(integrationText, pageWidth - margin * 2);
  doc.text(wrappedIntegration, margin, y);
  y += wrappedIntegration.length * 5 + 4;

  doc.setDrawColor(225, 225, 225);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;
  doc.setTextColor(120, 120, 120);
  doc.setFontSize(9);
  doc.text("Generated by Quantum Ledger Tax Workspace", margin, y);

  const fileName = `remittance-${cleanFileName(payload.taxType)}-${cleanFileName(payload.period)}.pdf`;
  doc.save(fileName);
  return paymentReference;
}
